package com.greenmango.entities;
// Generated Mar 30, 2019 11:34:21 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "green_mango")
public class Room implements java.io.Serializable {

	private Integer roomId;
	private String roomName;
	private Long fee;
	private String detail;
	private Integer totalRented;
	private Integer totalRentedMonth;

	public Room() {
	}

	public Room(String roomName, Long fee, String detail, Integer totalRented, Integer totalRentedMonth) {
		this.roomName = roomName;
		this.fee = fee;
		this.detail = detail;
		this.totalRented = totalRented;
		this.totalRentedMonth = totalRentedMonth;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "room_id", unique = true, nullable = false)
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@Column(name = "room_name", length = 50)
	public String getRoomName() {
		return this.roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	@Column(name = "fee")
	public Long getFee() {
		return this.fee;
	}

	public void setFee(Long fee) {
		this.fee = fee;
	}

	@Column(name = "detail", length = 65535)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "total_rented")
	public Integer getTotalRented() {
		return this.totalRented;
	}

	public void setTotalRented(Integer totalRented) {
		this.totalRented = totalRented;
	}

	@Column(name = "total_rented_month")
	public Integer getTotalRentedMonth() {
		return this.totalRentedMonth;
	}

	public void setTotalRentedMonth(Integer totalRentedMonth) {
		this.totalRentedMonth = totalRentedMonth;
	}

}
