package com.greenmango.entities;
// Generated Mar 30, 2019 11:34:21 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Summary generated by hbm2java
 */
@Entity
@Table(name = "summary", catalog = "green_mango")
public class Summary implements java.io.Serializable {

	private Integer no;
	private Date date;
	private Integer totalRented;
	private Long totalIncome;
	private Integer mostRent;

	public Summary() {
	}

	public Summary(Date date, Integer totalRented, Long totalIncome, Integer mostRent) {
		this.date = date;
		this.totalRented = totalRented;
		this.totalIncome = totalIncome;
		this.mostRent = mostRent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "no", unique = true, nullable = false)
	public Integer getNo() {
		return this.no;
	}

	public void setNo(Integer no) {
		this.no = no;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "total_rented")
	public Integer getTotalRented() {
		return this.totalRented;
	}

	public void setTotalRented(Integer totalRented) {
		this.totalRented = totalRented;
	}

	@Column(name = "total_income")
	public Long getTotalIncome() {
		return this.totalIncome;
	}

	public void setTotalIncome(Long totalIncome) {
		this.totalIncome = totalIncome;
	}

	@Column(name = "most_rent")
	public Integer getMostRent() {
		return this.mostRent;
	}

	public void setMostRent(Integer mostRent) {
		this.mostRent = mostRent;
	}

}
